server:
  port: 0

spring:
  application:
    name: ms-products
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:mem:market_products_db;MODE=PostgreSQL
