server:
  port: 0

spring:
  application:
    name: ms-auth
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:mem:market_auth_db;MODE=PostgreSQL
  redis:
    host: localhost
    port: 6379
